### ISSUE TITLE
Restore plugins

### ISSUE THREAD

**Issue by phanect** [phanect/configs#103]
The following plugins are now temporarily uninstalled in c136d95 because they are not ready for ESLint v9 and flat config yet.
Restore them when they are ready for the latest ESLint.

- [x] eslint-config-next
- [x] eslint-plugin-import[-x] (Restored by #135)
- [x] eslint-import-resolver-typescript (Restored by #135)
- [x] eslint-plugin-react (Restored by #112 and lint config package published by #126) 
- [x] eslint-plugin-react-hooks
